AWSTemplateFormatVersion: 2010-09-09
Description: S3 Sample

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
    Default: dev
  ProjectName:
    Type: String

Mappings:
  EnvMap:
    dev:
      S3BucketName: "sample-trigger-2112"

Resources:
  TriggerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [ EnvMap, !Ref Env, S3BucketName]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True



Outputs:
  S3BucketName:
    Value: !Ref TriggerBucket
