AWSTemplateFormatVersion: 2010-09-09
Description: VPC Sample

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
    Default: dev
  ProjectName:
    Type: String

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${Env}-${ProjectName}-vpc

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: !Sub ${Env}-${ProjectName}-vpc
