AWSTemplateFormatVersion: 2010-09-09
Description: Subnet Sample

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
    Default: dev
  ProjectName:
    Type: String

Resources:
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Env}-${ProjectName}-vpc
      CidrBlock: 192.168.1.0/16
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: !Sub ${Env}-${ProjectName}-private-subnet-1a

Outputs:
  PrivateSubnet1aId:
    Value: !Ref PrivateSubnet1a
    Export:
      Name: !Sub ${Env}-${ProjectName}-private-subnet-1a
