AWSTemplateFormatVersion: 2010-09-09
Description: VPC Endpoint Sample

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
    Default: dev
  ProjectName:
    Type: String

Resources:
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "*"
            Resource:
              - "*"
      RouteTableIds:
        - Fn::ImportValue: !Sub ${Env}-${ProjectName}-private-route-table-1a
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      VpcId:
        Fn::ImportValue: !Sub ${Env}-${ProjectName}-vpc

  LambdaEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Env}-${ProjectName}-vpc-endpoint-sg
      SubnetIds:
        - Fn::ImportValue: !Sub ${Env}-${ProjectName}-private-subnet-1a
      ServiceName: !Sub com.amazonaws.${AWS::Region}.lambda
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: !Sub ${Env}-${ProjectName}-vpc